import {createBackend} from '/src/backend.js';
import {setupViewport} from '/src/viewport.js';
setupViewport();document.title='Spot Now · simulazione locale 10.000 utenti';
const params=new URLSearchParams(location.search),delay=Number(params.get('delay')||200),me='10000000-0000-0000-0000-000000000001',venue='20000000-0000-0000-0000-000000000001';
const id=(prefix,n)=>`${prefix}000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const metrics={users:10000,matches:2000,messages:20000,delayMs:delay,requests:0,photoRequests:0,activePhotos:0,peakPhotos:0,activeReads:0,peakReads:0,errors:0,longTasks:[],actions:0};
let offline=false,slow=false;const blocked=new Set(),nonces=new Map(),interests=new Set();
const picture='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800"><rect width="600" height="800" fill="#25594f"/><circle cx="300" cy="280" r="90" fill="#57c6a0"/><path d="M90 650q0-230 210-230t210 230" fill="#57c6a0"/></svg>');
const users=Array.from({length:10000},(_,i)=>({id:id('1',i+1),name:`Utente ${String(i+1).padStart(6,'0')}`,age:25,gender:i%2?'F':'M',occupation:'Profilo fittizio',photo_path:`${id('1',i+1)}/photo.webp`,checked_in_at:new Date().toISOString(),expires_at:new Date(Date.now()+5400000).toISOString(),interest_sent:false}));
const matches=users.slice(1,2001).map((p,i)=>({id:id('4',i+1),person_id:p.id,name:p.name,age:p.age,photo_path:p.photo_path,venue_name:'Luogo simulato',created_at:new Date(Date.now()-i*1000).toISOString()}));
const messages=Array.from({length:20000},(_,i)=>({id:id('5',i+1),match_id:matches[0].id,sender_id:i%2?me:matches[0].person_id,body:`Messaggio fittizio ${i+1}`,created_at:new Date(Date.now()-2000000+i*100).toISOString()}));
const panel=document.createElement('aside');panel.className='load-panel';panel.innerHTML='<strong>SIMULAZIONE LOCALE</strong><p>Dati fittizi. Nessun account, messaggio o carico reale.</p><button id="loadOffline">Simula rete assente</button><button id="loadSlow">Simula rete lenta</button><pre id="loadMetrics"></pre>';
const style=document.createElement('style');style.textContent='.load-panel{position:fixed;left:14px;top:14px;width:270px;padding:16px;background:#24262e;border-radius:16px;font:13px Inter,sans-serif;z-index:25}.load-panel p{line-height:1.4;color:#ccc}.load-panel button{display:block;margin:8px 0;padding:10px;border:0;border-radius:8px}.load-panel pre{white-space:pre-wrap;line-height:1.5;font-size:11px}@media(max-width:900px){.load-panel{display:none}}';document.head.append(style);document.body.append(panel);
const output=()=>{metrics.domNodes=document.querySelectorAll('#phone *').length;metrics.cards=document.querySelectorAll('.screen.active .person,.screen.active .tribe-card').length;metrics.bubbles=document.querySelectorAll('#bubbles .bub').length;metrics.screen=document.querySelector('.screen.active')?.id;document.getElementById('loadMetrics').textContent=JSON.stringify(metrics,null,2);};
setInterval(output,300);document.addEventListener('click',()=>metrics.actions++);window.addEventListener('error',()=>metrics.errors++);window.addEventListener('unhandledrejection',()=>metrics.errors++);
try{new PerformanceObserver(list=>{for(const entry of list.getEntries()){metrics.longTasks.push(Math.round(entry.duration));if(metrics.longTasks.length>20)metrics.longTasks.shift();}}).observe({type:'longtask',buffered:true});}catch{}
document.getElementById('loadOffline').onclick=()=>{offline=!offline;document.getElementById('loadOffline').textContent=offline?'Ripristina rete':'Simula rete assente';};
document.getElementById('loadSlow').onclick=()=>{slow=!slow;document.getElementById('loadSlow').textContent=slow?'Ripristina velocità':'Simula rete lenta';};
async function response(data,photo=false){metrics.requests++;if(photo){metrics.photoRequests++;metrics.activePhotos++;metrics.peakPhotos=Math.max(metrics.peakPhotos,metrics.activePhotos);}else{metrics.activeReads++;metrics.peakReads=Math.max(metrics.peakReads,metrics.activeReads);}try{await new Promise(resolve=>setTimeout(resolve,slow?1500:delay));if(offline)throw Error('Failed to fetch');return {data};}finally{if(photo)metrics.activePhotos--;else metrics.activeReads--;}}
const client={auth:{getUser:()=>response({user:{id:me}})},storage:{from:()=>({createSignedUrls:paths=>response(paths.map(path=>({path,signedUrl:picture,error:null})),true),createSignedUrl:()=>response({signedUrl:picture},true)})},rpc:async(name,args={})=>{
 if(name==='location_people_page'){const live=args.live,entries=users.filter((p,i)=>p.id!==me&&!blocked.has(p.id)&&(i<1000)===live).map(p=>({...p,checked_in_at:live?p.checked_in_at:null,expires_at:live?p.expires_at:null,interest_sent:interests.has(p.id)}));return response(entries.slice(args.page_offset||0,(args.page_offset||0)+(args.page_size||49)).map(p=>({...p,total_count:entries.length})));}
 if(name==='my_matches_page'){const entries=matches.filter(m=>!blocked.has(m.person_id)&&(!args.requested_match||m.id===args.requested_match)&&(!args.requested_person||m.person_id===args.requested_person));return response(entries.slice(args.page_offset||0,(args.page_offset||0)+(args.page_size||49)).map(m=>({...m,total_count:entries.length})));}
 if(name==='send_message'){if(nonces.has(args.client_nonce))return response(nonces.get(args.client_nonce));const row={id:id('5',messages.length+1),match_id:args.target_match,sender_id:me,body:args.message_text,created_at:new Date().toISOString()};messages.push(row);nonces.set(args.client_nonce,row);return response(row);}
 if(name==='send_spot'){interests.add(args.target_user);return response(matches.find(m=>m.person_id===args.target_user)?.id||null);}
 if(name==='block_profile'){blocked.add(args.target_user);return response(null);}
 if(name==='report_profile')return response(null);
 throw Error(`Mock RPC missing: ${name}`);
},from:table=>{
 let matchId,before,limit=100;const query={select(){return this;},eq(key,value){if(key==='match_id')matchId=value;return this;},or(value){before=value.match(/^created_at\.lt\.(.+),and\(/)?.[1];return this;},order(){return this;},limit(n){limit=n;return this;},then(resolve,reject){if(table!=='messages')return Promise.reject(Error('Unexpected mock query')).then(resolve,reject);return response(messages.filter(m=>m.match_id===matchId&&(!before||m.created_at<before)).sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id)).slice(0,limit)).then(resolve,reject);}};return query;
}};
const backend=createBackend(client);Object.assign(backend,{session:async()=>({user:{id:me,is_anonymous:false}}),onSessionChange:()=>{},accountState:async()=> 'active',getProfile:async()=>({...users[0],preference:'ALL'}),ownCheckIn:async()=>({venue_id:venue,checked_in_at:new Date().toISOString(),expires_at:new Date(Date.now()+5400000).toISOString()}),getVenue:async()=>({id:venue,name:'Luogo simulato',address:'Test locale'}),tribes:()=>response(Array.from({length:10},(_,i)=>({id:id('2',i+1),name:`Luogo simulato ${i+1}`,member_count:10000,live_count:1000}))).then(r=>r.data),googleLogin:async()=>{throw Error('Accesso simulato: nessun redirect reale');},requestCode:async()=>{},uploadPhoto:async()=>`${me}/fake.webp`,saveProfile:async()=>{},deleteAccount:async()=>{throw Error('Nessuna cancellazione reale nella simulazione');}});
globalThis.__SPOT_LOAD_TEST_BACKEND__=backend;
await import('/src/live.js');output();
