import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {dom,Element,flush} from './helpers/dom.js';
const modalSource=(await readFile('src/modal.js','utf8')).replace('export function','function');
const installSource=(await readFile('src/install-app.js','utf8')).replace(/^import .*\n/gm,'').replace('export function','function');
const reportSource=(await readFile('src/report-prompt.js','utf8')).replace(/^import .*\n/gm,'').replace('export function','function');
function context(){const ui=dom();ui.screen('myprofile');ui.activate('myprofile');ui.get('phone').append(ui.get('myprofile'));const listeners={},stored=new Map();const window={addEventListener:(name,fn)=>listeners[name]=fn,dispatchEvent:event=>listeners[event.type]?.(event)};const ctx={document:ui.document,window,Event,crypto,navigator:{userAgent:'Android',onLine:true},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},userMessage:()=> 'Riprova.'};vm.createContext(ctx);vm.runInContext(modalSource,ctx);return {...ui,ctx,listeners,stored};}
test('PWA first-match prompt is dismissible, marked once and never displayed in standalone mode',()=>{
 const ui=context();vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ui.ctx);ui.ctx.install.showAfterMatch();const overlay=ui.get('phone').children.find(el=>el.id==='installAppOverlay');assert.equal(overlay.classList.contains('active'),true);assert.equal(ui.get('myprofile').inert,true);ui.ctx.install.close();assert.equal(ui.get('myprofile').inert,false);ui.ctx.install.showAfterMatch();assert.equal(overlay.classList.contains('active'),false);assert.equal(ui.stored.size,1);
 const standalone=context();standalone.ctx.matchMedia=()=>({matches:true});vm.runInContext(installSource+';globalThis.install=setupInstallApp();',standalone.ctx);standalone.ctx.install.showAfterMatch();assert.equal(standalone.get('phone').children.find(el=>el.id==='installAppOverlay').classList.contains('active'),false);
});
test('native Android prompt is called only on click, and iPhone instructions are explicit',async()=>{
 const ui=context();vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ui.ctx);let prompts=0;ui.listeners.beforeinstallprompt({preventDefault(){},prompt:async()=>{prompts++;},userChoice:Promise.resolve({outcome:'accepted'})});ui.ctx.install.showAfterMatch();assert.equal(prompts,0);const sheet=ui.get('phone').children.find(el=>el.id==='installAppOverlay').children[0];await sheet.children.find(el=>el.textContent==='Installa Soma').onclick();assert.equal(prompts,1);
 const ios=context();ios.ctx.navigator.userAgent='iPhone';vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ios.ctx);ios.ctx.install.showAfterMatch();const text=ios.get('phone').children.find(el=>el.id==='installAppOverlay').children[0].children[1].textContent;assert.match(text,/Safari/);assert.match(text,/Condividi/);
});
test('first-match invitation waits for another dialog rather than covering it',()=>{
 const ui=context();const other=new Element();other.className='overlay active';ui.get('phone').append(other);vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ui.ctx);ui.ctx.install.showAfterMatch();assert.equal(ui.stored.size,0);other.classList.remove('active');ui.listeners['spot-modal-closed']({});assert.equal(ui.stored.size,1);
});
test('failed report preserves details and reuses nonce when retried',async()=>{
 const ui=context();const nonces=[];ui.ctx.callbacks={onReport:async(_id,_reason,_details,_block,nonce)=>{nonces.push(nonce);if(nonces.length===1)throw new Error('offline');},onBlock:async()=>{}};vm.runInContext(reportSource+';globalThis.report=createReportPrompt(callbacks);',ui.ctx);ui.ctx.report.open('person');const overlay=ui.get('phone').children.at(-1),sheet=overlay.children[0];const reason=sheet.children[2],details=sheet.children[3];reason.value='other';details.value='Dettaglio di prova';sheet.onsubmit({preventDefault(){}});await flush();assert.equal(details.value,'Dettaglio di prova');assert.equal(overlay.classList.contains('active'),true);sheet.onsubmit({preventDefault(){}});await flush();assert.equal(nonces[0],nonces[1]);assert.equal(overlay.classList.contains('active'),false);
});
test('profile installation button remains visible and explains when the app is already saved',()=>{const ui=context();ui.ctx.matchMedia=()=>({matches:true});vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ui.ctx);const button=ui.get('myprofile').children.find(el=>el.id==='installAppButton');assert.equal(button.hidden,false);assert.equal(button.disabled,true);assert.match(button.textContent,/già salvata/);});
test('old invitation flag does not suppress the restored first-match invitation and appinstalled keeps profile action visible',()=>{const ui=context();ui.stored.set('spot-now-install-invitation','shown');vm.runInContext(installSource+';globalThis.install=setupInstallApp();',ui.ctx);ui.ctx.install.showAfterMatch();assert.equal(ui.get('phone').children.find(el=>el.id==='installAppOverlay').classList.contains('active'),true);ui.listeners.appinstalled();const button=ui.get('myprofile').children.find(el=>el.id==='installAppButton');assert.equal(button.hidden,false);assert.equal(button.disabled,true);assert.match(button.textContent,/già salvata/);});
