import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import {Image} from 'imagescript';import jpeg from 'jpeg-js';import {decode as decodePng} from 'fast-png';import decodeWebp,{init} from '@jsquash/webp/decode.js';import {database,seed,ids,asUser,admin} from './helpers/database.js';
test('existing JPEG, PNG and WebP produce small proportional previews and thumbnails without altering originals',async()=>{
 const source=await readFile('supabase/functions/photo-assets/index.ts','utf8'),context={Image,jpeg,decodePng,DataView,decodeWebp,init,WebAssembly,Uint8Array,Uint8ClampedArray,atob,btoa,Promise};vm.createContext(context);vm.runInContext(source.replace(/^import .*;$/mg,'').split("const headers=")[0].replace(/:Promise<void>\|undefined/,'').replace(/bytes:Uint8Array/,'bytes').replace(/\(globalThis as any\)/,'globalThis').replace(/data:Uint8ClampedArray,width:number,height:number/,'data,width,height').replace(/limit:number/,'limit').replace(/xx:number,yy:number/,'xx,yy'),context);
 const original=new Image(1600,800);original.fill(0x4280baff);
 for(const bytes of [await original.encodeJPEG(90),await original.encode(),await original.encodeWEBP(80)]){const saved=bytes.slice(),asset=await context.variants(bytes),thumb=await Image.decode(asset.thumbnail),preview=await Image.decode(Buffer.from(asset.preview.split(',')[1],'base64'));assert.equal(thumb.width,480);assert.equal(thumb.height,240);assert.equal(preview.width,120);assert.equal(preview.height,60);assert.ok(asset.thumbnail.length<50000);assert.ok(asset.preview.length<16000);assert.deepEqual(bytes,saved);}
 const large=new Image(5056,5056);large.fill(0x4280baff);const largeAsset=await context.variants(await large.encodeJPEG(80));assert.equal((await Image.decode(largeAsset.thumbnail)).width,480);
 const oriented=jpeg.encode({width:1600,height:800,data:original.bitmap,exifBuffer:Buffer.from('45786966000049492a0008000000010012010300010000000600000000000000','hex')},80).data;const rotated=await Image.decode((await context.variants(oriented)).thumbnail);assert.equal(rotated.width,240);assert.equal(rotated.height,480);
 await assert.rejects(context.variants(new Uint8Array([1,2,3])));
});
test('previews and thumbnails share profile permissions, restrict writes and disappear on account deletion',async t=>{
 const db=await database();t.after(()=>db.close());await seed(db);const path=ids.a+'/a.png',preview='data:image/jpeg;base64,YQ==';await db.exec(`insert into storage.objects(bucket_id,name) values('profile-photos','${path}.thumb.jpg');`);await asUser(db,ids.a);await db.query('select save_my_photo_preview($1,$2)',[path,preview]);await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[ids.b+'/b.png',preview]));await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[path,'data:text/html;base64,YQ==']));await assert.rejects(db.query('select * from pending_photo_assets()'));await assert.rejects(db.query('select * from spot_private.photo_assets'));await asUser(db,ids.b);assert.equal((await db.query('select * from photo_asset_status($1)',[path])).rows.length,0);assert.equal((await db.query('select name from storage.objects where name=$1',[path+'.thumb.jpg'])).rows.length,0);
 await asUser(db,ids.a);await db.query('select check_in($1)',[ids.q]);await asUser(db,ids.b);await db.query('select check_in($1)',[ids.q]);const rows=(await db.query('select * from location_people_photos_page($1,true)',[ids.v])).rows;assert.equal(rows.find(p=>p.id===ids.a).photo_preview,preview);assert.equal((await db.query('select name from storage.objects where name=$1',[path+'.thumb.jpg'])).rows.length,1);await db.query('select block_profile($1)',[ids.a]);assert.equal((await db.query('select * from photo_asset_status($1)',[path])).rows.length,0);await admin(db);await db.exec(`delete from public.profiles where id='${ids.a}'`);assert.equal((await db.query('select * from spot_private.photo_assets')).rows.length,0);
});

test('new uploads encode both lightweight variants in one decode and release the image',async t=>{
 const {photoVariants}=await import('../src/photo-variants.js');const originals={document:globalThis.document,createImageBitmap:globalThis.createImageBitmap,File:globalThis.File},dimensions=[];let closed=false;globalThis.createImageBitmap=async()=>({width:2400,height:1200,close:()=>closed=true});globalThis.document={createElement:()=>{const canvas={getContext:()=>({drawImage(){}}),toBlob(cb,type){dimensions.push([canvas.width,canvas.height]);cb(new Blob(['JPEG'],{type}));}};return canvas;}};t.after(()=>Object.assign(globalThis,originals));const result=await photoVariants(new Blob(['original']));assert.deepEqual(dimensions,[[120,60],[480,240]]);assert.equal(result.thumbnail.type,'image/jpeg');assert.equal(result.preview,'data:image/jpeg;base64,SlBFRw==');assert.ok(closed);
});
