import {createBoundedJpegEncoder}from'../supabase/functions/_shared/photo-jpeg-encoder.js';
import test from 'node:test';import assert from 'node:assert/strict';import {Image}from'imagescript';import jpeg from'jpeg-js';import pako from'../node_modules/.pnpm/pako@2.2.0/node_modules/pako/index.js';import webpFactory from'@jsquash/webp/codec/dec/webp_dec.js';import {inspectPhoto,checkPhotoDimensions,PHOTO_LIMITS,PhotoError}from'../src/photo-contract.js';import {createPhotoProcessor,readPhotoBody,resizePhoto,orientPhoto}from'../supabase/functions/_shared/photo-processing.js';import {decodePngBounded}from'../supabase/functions/_shared/photo-png.js';import {jpegWasm,webpWasm}from'../supabase/functions/_shared/photo-wasm.js';import {deflateSync}from'node:zlib';
const processor=kind=>createPhotoProcessor(kind,{Inflate:pako.Inflate,encoderFactory:createBoundedJpegEncoder,webpFactory});
function png(w,h,depth=8,payload=null){const t=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);return c>>>0;}),crc=b=>{let c=0xffffffff;for(const v of b)c=(c>>>8)^t[(c^v)&255];return(c^0xffffffff)>>>0;},chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(w);ihdr.writeUInt32BE(h,4);ihdr[8]=depth;ihdr[9]=2;return Buffer.concat([Buffer.from('\x89PNG\r\n\x1a\n','latin1'),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(payload??Buffer.alloc((w*3+1)*h))),chunk('IEND',Buffer.alloc(0))]);}
test('exact and above byte/side/pixel limits are independently enforced',async()=>{for(const [kind,max]of[['JPEG',12000000],['PNG',12000000],['WebP',6000000]]){checkPhotoDimensions(kind,4000,max/4000);assert.throws(()=>checkPhotoDimensions(kind,4000,max/4000+1),PhotoError);checkPhotoDimensions(kind,8192,1);assert.throws(()=>checkPhotoDimensions(kind,8193,1));assert.throws(()=>checkPhotoDimensions(kind,1,8193));assert.throws(()=>checkPhotoDimensions(kind,8192,8192));}const bytes=new Uint8Array(PHOTO_LIMITS.bytes);assert.equal((await readPhotoBody(new Request('https://test',{method:'POST',body:bytes}))).length,PHOTO_LIMITS.bytes);await assert.rejects(readPhotoBody(new Request('https://test',{method:'POST',body:new Uint8Array(PHOTO_LIMITS.bytes+1)})),e=>e.code==='SIZE');});
test('canonical JPEGs strip EXIF, GPS, comments, retain orientation and proportional dimensions for all formats',async()=>{const image=new Image(600,300);image.fill(0x4280baff);for(const [kind,bytes]of[['JPEG',await image.encodeJPEG(90)],['PNG',await image.encode()],['WebP',await image.encodeWEBP(80)]]){const original=bytes.slice(),p=processor(kind),asset=await p.process(bytes);assert.deepEqual(bytes,original);const d=inspectPhoto(asset.detail);assert.equal(d.width,600);assert.equal(d.height,300);assert.equal(d.orientation,1);assert.equal(inspectPhoto(asset.thumbnail).width,480);assert.equal(inspectPhoto(Buffer.from(asset.preview.split(',')[1],'base64')).width,120);assert.ok(!Buffer.from(asset.detail).includes(Buffer.from('Exif')));assert.ok(!Buffer.from(asset.detail).includes(Buffer.from('GPS')));assert.ok(!Buffer.from(asset.detail).includes(Buffer.from('comment')));await assert.rejects(p.process(bytes.slice(0,-7)));await p.process(bytes);}
 const encoded=jpeg.encode({width:600,height:300,data:image.bitmap,exifBuffer:Buffer.from('45786966000049492a0008000000010012010300010000000600000000000000','hex')},80).data;const rotated=await processor('JPEG').process(encoded);assert.equal(inspectPhoto(rotated.detail).width,300);assert.equal(inspectPhoto(rotated.detail).height,600);assert.ok(!Buffer.from(rotated.detail).includes(Buffer.from('Exif')));
});
test('PNG expansion must exactly match its declared rows; no full raster accumulation',async()=>{const p=processor('PNG');for(const data of[Buffer.alloc(4),Buffer.alloc(1000000)])await assert.rejects(p.process(png(2,2,8,data)),PhotoError);await assert.rejects(p.process(png(1,1,16)),e=>e.code==='DEPTH');const valid=png(2,2);await p.process(valid);const corrupted=Uint8Array.from(valid);corrupted[20]^=1;await assert.rejects(p.process(corrupted));await p.process(valid);const h=inspectPhoto(valid);assert.throws(()=>decodePngBounded(valid,h,pako.Inflate,{now:()=>2000,deadline:0}));});
test('false JPEG dimensions / multiple SOF / extra payload are rejected; decoded geometry is cross-checked',async()=>{const image=new Image(64,32);image.fill(0x123456ff);const bytes=await image.encodeJPEG(80),pos=Buffer.from(bytes).indexOf(Buffer.from([255,192]));assert.ok(pos>=0);const duplicate=Buffer.concat([bytes.subarray(0,pos),bytes.subarray(pos,pos+19),bytes.subarray(pos)]);assert.throws(()=>inspectPhoto(duplicate));assert.throws(()=>inspectPhoto(Buffer.concat([bytes,Buffer.from([0])])));const plausible=Uint8Array.from(bytes);plausible[pos+8]=32;await assert.rejects(processor('JPEG').process(plausible));const falseSize=bytes.slice();falseSize[pos+7]=255;falseSize[pos+8]=255;assert.throws(()=>inspectPhoto(falseSize));});
test('PNG bilinear matches reference resize and explicitly flattens transparency onto white',async()=>{const image=new Image(1602,10);for(let y=0;y<10;y++)for(let x=0;x<1602;x++)image.setPixelAt(x+1,y+1,((x%256)<<24)|((y*20)<<16)|0x4000|128);const bytes=await image.encode(),h=inspectPhoto(bytes),p=decodePngBounded(bytes,h,pako.Inflate),reference=resizePhoto({width:1602,height:10,data:image.bitmap},1600);assert.equal(p.width,reference.width);assert.equal(p.height,reference.height);for(let i=0;i<p.data.length;i++)assert.ok(Math.abs(p.data[i]-reference.data[i])<=1);const a=await processor('PNG').process(bytes),d=jpeg.decode(a.detail);assert.ok(d.data[0]>100);});
test('WASM memory cannot grow beyond 96/64 MiB',async()=>{const j=new WebAssembly.Instance(await WebAssembly.compile(Buffer.from(jpegWasm,'base64'))).exports.memory;assert.throws(()=>j.grow(1536));let memory;await webpFactory({noInitialRun:true,instantiateWasm:(imports,cb)=>{const i=new WebAssembly.Instance(new WebAssembly.Module(Buffer.from(webpWasm,'base64')),imports);memory=i.exports.s||Object.values(i.exports).find(v=>v instanceof WebAssembly.Memory);cb(i);return i.exports;}});assert.ok(memory instanceof WebAssembly.Memory);assert.throws(()=>memory.grow(1024),RangeError);});
test('worker busy and memory pressure reject safely; exceptions release processing lock',async()=>{const image=new Image(64,32);image.fill(0x123456ff);const bytes=await image.encodeJPEG();const p=processor('JPEG'),first=p.process(bytes);await assert.rejects(p.process(bytes),e=>e.code==='BUSY');await first;await assert.rejects(p.process(new Uint8Array([1,2,3])));await p.process(bytes);await assert.rejects(createPhotoProcessor('JPEG',{encodeJpeg:jpeg.encode,memory:()=>({heapTotal:200*1048576,external:0})}).process(bytes),e=>e.code==='BUSY');});

test('PNG filters 0–4 work for all 8-bit color types, including indexed transparency; invalid palette indices reject',async()=>{
 const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);let c=0xffffffff;for(const v of b.subarray(4,-4)){c^=v;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}b.writeUInt32BE((c^0xffffffff)>>>0,b.length-4);return b;};
 for(const [type,channels]of [[0,1],[2,3],[3,1],[4,2],[6,4]])for(let filter=0;filter<5;filter++){
 const w=4,h=3,stride=w*channels,raw=Buffer.alloc((stride+1)*h),previous=new Uint8Array(stride);for(let y=0;y<h;y++){raw[y*(stride+1)]=filter;const row=Uint8Array.from({length:stride},(_,i)=>type===3?(i+y)%2:(i*29+y*17)%256);for(let i=0;i<stride;i++){const a=i>=channels?row[i-channels]:0,b=previous[i],c=i>=channels?previous[i-channels]:0,p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c),predict=filter===1?a:filter===2?b:filter===3?(a+b)>>>1:filter===4?pa<=pb&&pa<=pc?a:pb<=pc?b:c:0;raw[y*(stride+1)+1+i]=(row[i]-predict)&255;}previous.set(row);}
 const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(w);ihdr.writeUInt32BE(h,4);ihdr[8]=8;ihdr[9]=type;const palette=type===3?[chunk('PLTE',Buffer.from([255,0,0,0,0,255])),chunk('tRNS',Buffer.from([0,255]))]:[];const bytes=Buffer.concat([Buffer.from('\x89PNG\r\n\x1a\n','latin1'),chunk('IHDR',ihdr),...palette,chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);const pixels=decodePngBounded(bytes,inspectPhoto(bytes),pako.Inflate);assert.equal(pixels.width,w);if(type===3){assert.deepEqual([...pixels.data.subarray(0,4)],[255,255,255,255]);assert.deepEqual([...pixels.data.subarray(4,8)],[0,0,255,255]);if(filter===0){const bad=Buffer.from(raw);bad[1]=2;const corrupt=Buffer.concat([Buffer.from('\x89PNG\r\n\x1a\n','latin1'),chunk('IHDR',ihdr),...palette,chunk('IDAT',deflateSync(bad)),chunk('IEND',Buffer.alloc(0))]);assert.throws(()=>decodePngBounded(corrupt,inspectPhoto(corrupt),pako.Inflate),PhotoError);}}
 }
});

test('WebP canvas dimensions cannot conceal contradictory payload geometry',async()=>{
 const image=new Image(64,32);image.fill(0x4280baff);const original=Buffer.from(await image.encodeWEBP(80)),body=original.subarray(12),canvas=Buffer.alloc(18);canvas.write('VP8X');canvas.writeUInt32LE(10,4);canvas[12]=64;canvas[15]=31;const bytes=Buffer.concat([original.subarray(0,12),canvas,body]);bytes.writeUInt32LE(bytes.length-8,4);assert.throws(()=>inspectPhoto(bytes),PhotoError);const p=processor('WebP');await p.process(original);await assert.rejects(p.process(original.subarray(0,original.length-3)));await p.process(original);
});
