import test from 'node:test';import assert from 'node:assert/strict';import {photoUploadHandler} from '../supabase/functions/_shared/photo-upload.js';import {photoWorker}from'../supabase/functions/_shared/photo-worker.js';
function endpoint({valid=true,anonymous=false,legacy=false}={}){const calls=[],admin={auth:{getUser:async token=>{calls.push(['auth',token]);return{data:{user:valid?{id:'caller',is_anonymous:anonymous}:null},error:valid?null:{}};}},rpc:async name=>{calls.push(['rpc',name]);return name==='photo_needs_normalization'?{data:legacy}:{data:[]};},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{photo_path:'caller/current'}})})})}),storage:{from:()=>{throw Error('Unexpected storage');}}};return{handler:photoUploadHandler({admin,url:'https://test',serviceKey:'service',fetcher:async()=>new Response('{}',{status:403})}),calls};}
const request=body=>new Request('https://test',{method:'POST',headers:{Authorization:'Bearer user-token','Content-Type':'application/json'},body:JSON.stringify(body)});
test('photo pipeline rejects missing/anonymous credentials and forged ownership before reading private objects',async()=>{const e=endpoint();assert.equal((await e.handler(new Request('https://test',{method:'POST',body:'{}'}))).status,401);assert.equal(e.calls.length,0);assert.equal((await e.handler(request({photo_path:'someone/photo'}))).status,403);assert.equal((await endpoint({valid:false}).handler(request({photo_path:'caller/current'}))).status,401);assert.equal((await endpoint({anonymous:true}).handler(request({photo_path:'caller/current'}))).status,401);assert.equal((await e.handler(request({photo_path:'caller/old'}))).status,403);});
test('user cannot backfill/select another account and canonical compatibility call avoids decoding',async()=>{const e=endpoint();assert.equal((await e.handler(request({backfill:true,user_id:'victim'}))).status,409);const r=await e.handler(request({photo_path:'caller/current'}));assert.equal(r.status,200);assert.equal((await r.json()).ready,true);});
test('internal codec endpoints never accept anonymous or user tokens',async()=>{let decoded=0;const worker=photoWorker({process:async()=>decoded++},{serviceKey:'service'});for(const auth of['','Bearer user','Bearer wrong'])assert.equal((await worker(new Request('https://test',{method:'POST',headers:{Authorization:auth},body:'x'}))).status,403);assert.equal(decoded,0);});

test('malformed upload releases lease using SDK thenable without catch and preserves rejection response',async()=>{
 const calls=[];const admin={auth:{getUser:async()=>({data:{user:{id:'caller',is_anonymous:false}}})},rpc:(name)=>({then(resolve){calls.push(name);resolve({data:name==='begin_photo_upload'?{photo_path:'caller/test.jpg',lease_token:'lease'}:null,error:null});}})};
 const handler=photoUploadHandler({admin,url:'https://test',serviceKey:'service'});
 const r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer user','X-Photo-Request-Id':'40000000-0000-4000-8000-000000000001'},body:'not-an-image'}));
 assert.equal(r.status,422);assert.equal((await r.json()).code,'FORMAT');assert.deepEqual(calls,['begin_photo_upload','fail_photo_upload']);
 const again=await handler(new Request('https://test',{method:'POST'}));assert.equal(again.status,401);
});

test('production legacy gate preserves current reference without reading or processing original',async()=>{const e=endpoint({legacy:true});const r=await e.handler(request({photo_path:'caller/current'}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{ready:true,photo_path:'caller/current',legacy_normalization_skipped:true});assert.ok(!e.calls.some(c=>c[1]==='begin_photo_upload'));assert.equal((await e.handler(request({backfill:true}))).status,409);});
