import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import {Image} from 'imagescript';import jpeg from 'jpeg-js';import {decode as decodePng} from 'fast-png';import decodeWebp,{init} from '@jsquash/webp/decode.js';import {database,seed,ids,asUser,admin} from './helpers/database.js';
test('previews and thumbnails share profile permissions, restrict writes and disappear on account deletion',async t=>{
 const db=await database();t.after(()=>db.close());await seed(db);const path=ids.a+'/a.png',preview='data:image/jpeg;base64,YQ==';await db.exec(`insert into storage.objects(bucket_id,name) values('profile-photos','${path}.thumb.jpg');`);await asUser(db,ids.a);await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[path,preview]));await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[ids.b+'/b.png',preview]));await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[path,'data:text/html;base64,YQ==']));await assert.rejects(db.query('select * from pending_photo_assets()'));await assert.rejects(db.query('select * from spot_private.photo_assets'));await asUser(db,ids.b);assert.equal((await db.query('select * from photo_asset_status($1)',[path])).rows.length,0);assert.equal((await db.query('select name from storage.objects where name=$1',[path+'.thumb.jpg'])).rows.length,0);
 await asUser(db,ids.a);await db.query('select check_in($1)',[ids.q]);await asUser(db,ids.b);await db.query('select check_in($1)',[ids.q]);const rows=(await db.query('select * from location_people_photos_page($1,true)',[ids.v])).rows;assert.equal(rows.find(p=>p.id===ids.a).photo_preview,preview);assert.equal((await db.query('select name from storage.objects where name=$1',[path+'.thumb.jpg'])).rows.length,1);await db.query('select block_profile($1)',[ids.a]);assert.equal((await db.query('select * from photo_asset_status($1)',[path])).rows.length,0);await admin(db);await db.exec(`delete from public.profiles where id='${ids.a}'`);assert.equal((await db.query('select * from spot_private.photo_assets where user_id=$1',[ids.a])).rows.length,0);
});

test('new uploads encode both lightweight variants in one decode and release the image',async t=>{
 const {photoVariants}=await import('../src/photo-variants.js');const originals={document:globalThis.document,createImageBitmap:globalThis.createImageBitmap,File:globalThis.File},dimensions=[];let closed=false;globalThis.createImageBitmap=async()=>({width:2400,height:1200,close:()=>closed=true});globalThis.document={createElement:()=>{const canvas={getContext:()=>({drawImage(){}}),toBlob(cb,type){dimensions.push([canvas.width,canvas.height]);cb(new Blob(['JPEG'],{type}));}};return canvas;}};t.after(()=>Object.assign(globalThis,originals));const result=await photoVariants(new Blob(['original']));assert.deepEqual(dimensions,[[120,60],[480,240],[1600,800]]);assert.equal(result.thumbnail.type,'image/jpeg');assert.equal(result.preview,'data:image/jpeg;base64,SlBFRw==');assert.ok(closed);
});

test('HD derivatives inherit profile access and cannot be prepared by another user',async t=>{
 const db=await database();t.after(()=>db.close());await seed(db);const path=ids.a+'/a.png',hd=path+'.detail.jpg',preview='data:image/jpeg;base64,YQ==';await db.exec(`insert into storage.objects(bucket_id,name) values('profile-photos','${path}.thumb.jpg'),('profile-photos','${hd}');`);
 await asUser(db,ids.a);await assert.rejects(db.query('select save_my_photo_preview($1,$2)',[path,preview]));assert.equal((await db.query('select * from photo_asset_status($1)',[path])).rows[0].detail_path,hd);await assert.rejects(db.query('select store_photo_assets_hd($1,$2,$3,$4)',[path,preview,path+'.thumb.jpg',hd]));
 await asUser(db,ids.b);assert.equal((await db.query('select name from storage.objects where name=$1',[hd])).rows.length,0);await asUser(db,ids.a);await db.query('select check_in($1)',[ids.q]);await asUser(db,ids.b);await db.query('select check_in($1)',[ids.q]);const visible=(await db.query('select * from location_people_photos_page($1,true)',[ids.v])).rows;assert.equal(visible.find(p=>p.id===ids.a).detail_path,hd);assert.equal((await db.query('select name from storage.objects where name=$1',[hd])).rows.length,1);await db.query('select block_profile($1)',[ids.a]);assert.equal((await db.query('select name from storage.objects where name=$1',[hd])).rows.length,0);await admin(db);await db.exec(`delete from public.profiles where id='${ids.a}'`);assert.equal((await db.query('select * from spot_private.photo_assets where user_id=$1',[ids.a])).rows.length,0);
});
