import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {dom,Element,deferred,flush} from './helpers/dom.js';
const source=(await readFile(new URL('../src/scanner.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace('export function','function');
async function setup(){const ui=dom(),screen=ui.screen('camera'),finder=new Element(),hint=new Element();finder.className='viewfinder';hint.className='camhint';screen.append(finder,hint);const instances=[];class Scanner{constructor(video,callback){this.callback=callback;this.starting=deferred();this.destroyed=false;instances.push(this);}start(){return this.starting.promise;}destroy(){this.destroyed=true;}}
const context={document:ui.document,QrScanner:Scanner,venueTokenFromQr:data=>data==='valid'?'token':null,location:{origin:'https://spot.example'},scans:[]};vm.createContext(context);vm.runInContext(source+`;this.controller=createVenueScanner({screen:testScreen,onScan:async token=>scans.push(token),onBack:()=>{}});`,Object.assign(context,{testScreen:screen}));return {controller:context.controller,instances,start:screen.children.find(e=>e.className.includes('btn-primary')),hint,scans:context.scans};}
test('late camera startup failure cannot stop a newly activated camera',async()=>{const ui=await setup();const older=ui.start.onclick();ui.controller.stop();const newer=ui.start.onclick();ui.instances[0].starting.reject(new Error('camera'));await older;assert.equal(ui.instances[1].destroyed,false);ui.instances[1].starting.resolve();await newer;assert.match(ui.hint.textContent,/Inquadra/);});
test('stale camera callbacks and double scans cannot open a second venue',async()=>{const ui=await setup();const starting=ui.start.onclick();ui.instances[0].starting.resolve();await starting;await ui.instances[0].callback({data:'other'});assert.equal(ui.scans.length,0);await ui.instances[0].callback({data:'valid'});await ui.instances[0].callback({data:'valid'});assert.deepEqual([...ui.scans],['token']);assert.equal(ui.instances[0].destroyed,true);});

test('entering scanner immediately requests camera and repeated open does not restart it',async()=>{const ui=await setup();ui.controller.open();ui.controller.open();assert.equal(ui.instances.length,1);assert.equal(ui.start.hidden,true);ui.instances[0].starting.resolve();await flush();assert.match(ui.hint.textContent,/Inquadra/);});
test('denied camera exposes an explicit retry without leaving scanner',async()=>{const ui=await setup();ui.controller.open();ui.instances[0].starting.reject(new Error('denied'));await flush();assert.equal(ui.start.hidden,false);assert.match(ui.hint.textContent,/non disponibile/);});
