import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
test('Tribe permissions, exact expiry, multi-location membership and persistent reciprocity',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,is_anonymous boolean not null default false);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
 alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;`);
 for(const f of (await readdir('supabase/migrations')).sort())await db.exec(await readFile(`supabase/migrations/${f}`,'utf8'));
 const a='10000000-0000-0000-0000-000000000001',b='10000000-0000-0000-0000-000000000002',c='10000000-0000-0000-0000-000000000003';
 const v='20000000-0000-0000-0000-000000000001',w='20000000-0000-0000-0000-000000000002',q='30000000-0000-0000-0000-000000000001',r='30000000-0000-0000-0000-000000000002';
 await db.exec(`insert into auth.users values('${a}',false),('${b}',false),('${c}',true);
 insert into spot_private.validated_photos(photo_path,user_id,preview,canonical_sha,canonical_bytes,source_format,source_width,source_height) values('${a}/a.png','${a}','data:image/jpeg;base64,YQ==',repeat('a',64),1,'PNG',1,1),('${b}/b.png','${b}','data:image/jpeg;base64,YQ==',repeat('a',64),1,'PNG',1,1),('${c}/c.png','${c}','data:image/jpeg;base64,YQ==',repeat('a',64),1,'PNG',1,1);
 insert into public.profiles values('${a}','Anna',24,'F','ALL','${a}/a.png',now()),('${b}','Luca',26,'M','ALL','${b}/b.png',now()),('${c}','Anon',25,'M','ALL','${c}/c.png',now());
 insert into public.venues(id,name,address) values('${v}','Gym','Test'),('${w}','Campus','Test');insert into spot_private.venue_codes values('${v}','${q}'),('${w}','${r}');`);
 const asUser=async id=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`);
 const count=async live=>(await db.query(`select * from public.location_people('${v}',${live})`)).rows;
 await asUser(a);await db.query(`select public.check_in('${q}')`);await db.query(`select public.check_in('${q}')`);
 await asUser(b);await db.query(`select public.check_in('${q}')`);
 await db.exec(`reset role;insert into storage.objects(bucket_id,name) values('profile-photos','${b}/b.png');`);
 await asUser(a);assert.equal((await db.query(`select * from storage.objects where name='${b}/b.png'`)).rows.length,1);assert.equal((await count(true)).length,1);assert.equal((await count(false)).length,0);
 await assert.rejects(db.query(`select * from public.location_people('${w}',false)`));
 await db.exec(`reset role;update public.checkins set checked_in_at=now()-interval '90 minutes',expires_at=now() where user_id='${b}';`);
 await asUser(a);assert.equal((await count(true)).length,0);const tribe=await count(false);assert.equal(tribe.length,1);assert.equal(tribe[0].checked_in_at,null);assert.equal(tribe[0].expires_at,null);
 await db.query(`select public.send_spot('${b}','${v}')`);
 await db.query(`select public.check_in('${r}')`);assert.equal((await db.query('select * from public.my_tribes()')).rows.length,2);
 await db.exec(`reset role;update spot_private.interests set created_at=now()-interval '1 year';`);
 await asUser(b);const match=(await db.query(`select public.send_spot('${a}','${v}') as id`)).rows[0].id;assert.ok(match);
 await db.exec(`reset role;update public.matches set created_at=now()-interval '1 year';`);
 await asUser(a);assert.equal((await db.query('select * from public.my_matches()')).rows.length,1);
 await db.query(`insert into public.blocks values('${a}','${b}',now())`);assert.equal((await count(false)).length,0);assert.equal((await db.query('select * from public.my_matches()')).rows.length,0);
 assert.equal((await db.query(`select * from storage.objects where name='${b}/b.png'`)).rows.length,0);
 await db.exec(`reset role;delete from public.blocks;insert into spot_private.suspensions(user_id,reason) values('${b}','Test');`);
 await asUser(a);assert.equal((await count(false)).length,0);
 await assert.rejects(db.query(`select public.prepare_account_deletion('${b}')`));
 await db.exec(`reset role;delete from spot_private.suspensions;`);
 await asUser(c);await assert.rejects(db.query(`select public.check_in('${q}')`));await assert.rejects(db.query(`select * from public.location_people('${v}',false)`));
 await db.exec('reset role;set role anon;');const preview=(await db.query(`select * from public.venue_preview('${q}')`)).rows[0];assert.equal(preview.member_count,2);await assert.rejects(db.query('select * from public.profiles'));
 await db.exec(`reset role;`);const members=(await db.query(`select * from spot_private.tribe_memberships where user_id='${a}'`)).rows;assert.equal(members.length,2);
 await db.query(`select public.prepare_account_deletion('${b}')`);await db.query(`delete from auth.users where id='${b}'`);
 assert.equal((await db.query(`select * from spot_private.tribe_memberships where user_id='${b}'`)).rows.length,0);
 assert.equal((await db.query('select * from public.matches')).rows.length,0);
 }finally{await db.close();}
});
